name: Main
on:
  push:
    paths-ignore:
      - '**.md'
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - 'index.html'

jobs: 
  tests:
    runs-on: ubuntu-latest
    if: "!startsWith(github.ref, 'refs/tags/')"
    container: 
      image: cubicrootxyz/matrix-go:1.21
      options: --user root
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Run tests
        run: go test ./...

  lint:
    runs-on: ubuntu-latest
    if: "!startsWith(github.ref, 'refs/tags/')"
    container: 
      image: cubicrootxyz/matrix-go:1.21
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - name: Run golangci
        run: golangci-lint run --timeout 3m0s